version: "3.9"
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - web
      - server

  web:
    build:
      context: ./frontend/
      dockerfile: Dockerfile

  server:
    build:
      context: ./backend/app/
      dockerfile: Dockerfile
volumes:
  logvolume01: { }